org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=false
systemProp.java.net.preferIPv4Stack=true

mod_id=tconjei
mod_name=TConJEI
mod_license=MIT License
mod_version=1.6.0
mod_group_id=me.paypur.tconjei
mod_authors=paypur
mod_description=A JEI addon for Tinker's Construct 3

minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)
neo_version=21.1.241
neo_range=[21.1.0,21.2.0)
loader_range=[4,)
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

mantle_version=1.12.3
mantle_range=[1.12.3,)
tconstruct_version=3.12.3
tconstruct_range=[3.12.3,)
jei_version=19.39.0.368
jei_range=[19.0.0,20.0.0)
