modLoader="javafml"
loaderVersion="${loader_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/paypur/TConJEI/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tconjei"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="mantle"
type="required"
versionRange="${mantle_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="tconstruct"
type="required"
versionRange="${tconstruct_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
type="required"
versionRange="${jei_range}"
ordering="AFTER"
side="CLIENT"
